name: Build application
on: 
  workflow_dispatch:
  push:
    branches: 
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.4
      with:
        java-version: '11'
    - name: Checkout code
      uses: actions/checkout@v3.5.3
    - name: Build with maven
      run: mvn install
    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: target/*.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: echo 'Deploy...'
      
    
    
  
  
  
